name: Update CHANGELOG
on: 
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Fetch changes
        run: git fetch --prune --tags --unshallow
    
      - 
        name: Install git-chglog
        # v1
        uses: craicoverflow/install-git-chglog@fd5ace93851e0e2a8deb0b3c31a07c79cb76fcf2

      -
        name: Generate a CHANGELOG
        run: git-chglog -o CHANGELOG.md

        # v4
      - uses: stefanzweifel/git-auto-commit-action@0b492c0d951b87f3cd12523a542dbd156c1dbc80
        with:
          branch: main
          file_pattern: CHANGELOG.md
          commit_message: 'chore: update CHANGELOG'